### ISSUE TITLE
Porting `poly.jl` to C++

### ISSUE THREAD

**Issue by terasakisatoshi** [SpM-lab/libsparseir#23]
https://github.com/SpM-lab/SparseIR.jl/blob/main/src/poly.jl

**Comment by shinaoka** [comment]
The existing tests in Julia depends on sve.jl, but they should not.
https://github.com/SpM-lab/SparseIR.jl/blob/main/test/poly.jl

How about implementing a few more fundamental tests in Julia, before porting `poly.jl` to C++.

**Comment by shinaoka** [comment]
I have implemented two tests.
https://github.com/SpM-lab/SparseIR.jl/issues/51

**Comment by shinaoka** [comment]
Be careful.
https://github.com/SpM-lab/SparseIR.jl/issues/50
